# Generated by Django 2.1.4 on 2018-12-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=7)),
                ('teammate_1', models.CharField(max_length=30)),
                ('teammate_2', models.CharField(max_length=30)),
                ('teammate_3', models.CharField(max_length=30)),
                ('teammate_4', models.CharField(max_length=30)),
                ('outcome', models.CharField(max_length=4)),
                ('mute', models.CharField(max_length=3)),
                ('attitude_Score', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
