# Generated by Django 2.1.4 on 2018-12-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataform',
            name='champion',
            field=models.CharField(default='', max_length=30),
        ),
    ]
